Add apply_discount_factor to gas_parameters
eosnetworkfoundation/evmone pull request #15
Opened 2024-10-28 17:54 UTC by elmato

2025-01-14 00:24 UTC, yarkinwho requested changes

2025-01-14 00:24 UTC, yarkinwho commented on lib/evmone/execution_state.hpp
> +        const intx::uint256 den(intx::uint256(base_fee_per_gas) + intx::uint256(inclusion_price));
using numerator and denominator maybe better? but it's fine to leave it alone.

2025-01-14 00:24 UTC, yarkinwho commented on lib/evmone/execution_state.hpp
> +            const auto gas_consumed = std::max(d, decltype(d){0});
no need to use decltype as we know it's int64_t

2025-01-14 00:24 UTC, yarkinwho commented on lib/evmone/execution_state.hpp
> +            const auto gas_consumed = std::max(d, decltype(d){0});
no need to use decltype as we know it's int64_t

2025-01-14 00:24 UTC, yarkinwho commented on lib/evmone/execution_state.hpp
> +        cpu_gas_refund_ = std::max(-y, decltype(y){0});
is it possible to eliminate the use of auto and decltype here? it seems a little bit dangerous to me to use things like auto and decltype in the scenarios that have the risk of overflow/underflow.

2025-01-20 07:08 UTC, yarkinwho commented on lib/evmone/execution_state.hpp
> +        cpu_gas_refund_ = std::max(-y, decltype(y){0});
I wonder if change the auto above as well can help fixing this?

2025-01-20 20:59 UTC, elmato commented on lib/evmone/execution_state.hpp
> +        cpu_gas_refund_ = std::max(-y, decltype(y){0});
fixed

2025-01-22 02:05 UTC, yarkinwho approved these changes

2025-01-22 03:29 UTC, merged